### ISSUE TITLE
How Button Edit,Delete And View Rendered??

### ISSUE THREAD

**Issue by rickyanwar** [Riyadhahmed/laravel-ajax-crud-yajra-datatable#1]
Can You Explaine why button edit,view,and delete be render in datatables?
![Screenshot from 2019-09-18 01-22-31](https://user-images.githubusercontent.com/36995966/65064796-b7f26400-d9b3-11e9-8ded-1a1974cc9c67.png)

**Comment by Riyadhahmed** [comment]
are you asking me about how it render? or why it render?

how?
you see in controller page  allUsers() function

i add

add_column('action') and include an action page


why ?

render it for dynamic CRUD

cz after that you don't need to refresh the page while doing any kind of
operation create, read ,edit delete
